config/routes.rb
Rails.application.routes.draw do
  resources :inproceedings
  resources :articles
  resources :books

  root 'application#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :citation_key, uniqueness: true
  validates :author, presence: true
  validates :title, presence: true
  validates :journal, presence: true
  validates :year, presence: true

end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/models/inproceeding.rb
class Inproceeding < ActiveRecord::Base
  validates :citation_key, uniqueness: true
  validates :author, presence: true
  validates :title, presence: true
  validates :booktitle, presence: true
  validates :year, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def index
    @books = Book.all
    @articles = Article.all
    @inproceedings = Inproceeding.all
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      elses
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:citation_key, :author, :title, :journal, :volume, :year, :number, :pages, :month, :note, :volume, :key)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Uusi viite lisätty.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:citation_key, :author, :title, :publisher, :year, :volume, :series, :address, :edition, :month, :note, :key)
    end
end

app/controllers/inproceedings_controller.rb
class InproceedingsController < ApplicationController
  before_action :set_inproceeding, only: [:show, :edit, :update, :destroy]

  # GET /inproceedings
  # GET /inproceedings.json
  def index
    @inproceedings = Inproceeding.all
  end

  # GET /inproceedings/1
  # GET /inproceedings/1.json
  def show
  end

  # GET /inproceedings/new
  def new
    @inproceeding = Inproceeding.new
  end

  # GET /inproceedings/1/edit
  def edit
  end

  # POST /inproceedings
  # POST /inproceedings.json
  def create
    @inproceeding = Inproceeding.new(inproceeding_params)

    respond_to do |format|
      if @inproceeding.save
        format.html { redirect_to @inproceeding, notice: 'Inproceeding was successfully created.' }
        format.json { render :show, status: :created, location: @inproceeding }
      else
        format.html { render :new }
        format.json { render json: @inproceeding.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inproceedings/1
  # PATCH/PUT /inproceedings/1.json
  def update
    respond_to do |format|
      if @inproceeding.update(inproceeding_params)
        format.html { redirect_to @inproceeding, notice: 'Inproceeding was successfully updated.' }
        format.json { render :show, status: :ok, location: @inproceeding }
      else
        format.html { render :edit }
        format.json { render json: @inproceeding.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inproceedings/1
  # DELETE /inproceedings/1.json
  def destroy
    @inproceeding.destroy
    respond_to do |format|
      format.html { redirect_to inproceedings_url, notice: 'Inproceeding was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inproceeding
      @inproceeding = Inproceeding.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inproceeding_params
      params.require(:inproceeding).permit(:citation_key, :author, :title, :booktitle, :year, :editor, :pages, :organization, :address, :month, :note, :key)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/inproceedings_helper.rb
module InproceedingsHelper
end

app/views/application/index.html.erb
<h1>All references in BibTeX format:</h1>

<% @books.each do |book| %>
    <p>@Book{<%= book.citation_key %>,<br>
      author = "<%= book.author %>", <br>
      title = "<%= book.title %>",<br>
      publisher = "<%= book.publisher %>",<br>
      year = <%= book.year %>, <br>
      <% if not book.volume.empty? %> volume = "<%= book.volume %>", <br>
      <% end %>
      <% if not book.series.empty? %> series = "<%= book.series %>", <br>
      <% end %>
      <% if not book.address.empty? %> address = "<%= book.address %>", <br>
      <% end %>
      <% if not book.edition.empty? %> edition = "<%= book.edition %>", <br>
      <% end %>
      <% if not book.month.empty? %> month = "<%= book.month %>", <br>
      <% end %>
      <% if not book.note.empty? %> note = "<%= book.note %>", <br>
      <% end %>
      <% if not book.key.empty? %> key = "<%= book.key %>", <br>
      <% end %>
      }
    </p>
<% end %>
<% @inproceedings.each do |inproceeding| %>
    <p>@inproceedings{<%= inproceeding.citation_key %>,<br>
      author = "<%= inproceeding.author %>", <br>
      title = "<%= inproceeding.title %>",<br>
      booktitle = "<%= inproceeding.booktitle %>",<br>
      year = <%= inproceeding.year %>, <br>
      <% if not inproceeding.editor.empty? %> editor = "<%= inproceeding.editor %>", <br>  <% end %>
      <% if not inproceeding.pages.empty? %> pages = "<%= inproceeding.pages %>", <br> <% end %>
      <% if not inproceeding.organization.empty? %> organization = "<%= inproceeding.organization %>", <br> <% end %>
      <% if not inproceeding.address.empty? %> address = "<%= inproceeding.address %>", <br> <% end %>
      <% if not inproceeding.month.empty? %> month = "<%= inproceeding.month %>", <br> <% end %>
      <% if not inproceeding.note.empty? %> note = "<%= inproceeding.note %>", <br> <% end %>
      <% if not inproceeding.key.empty? %> key = "<%= inproceeding.key %>", <br> <% end %>
      }
    </p>
<% end %>
<% @articles.each do |article| %>
    <p>@article{<%= article.citation_key %>,<br>
      author = "<%= article.author %>", <br>
      title = "<%= article.title %>",<br>
      booktitle = "<%= article.journal %>",<br>
      year = <%= article.year %>, <br>
      <% if not article.volume.empty? %> volume = "<%= article.volume %>", <br>
      <% end %>
      <% if not article.number<0 %> number = "<%= article.number %>", <br>
      <% end %>
      <% if not article.pages.empty? %> pages = "<%= article.pages %>", <br>
      <% end %>
      <% if not article.month.empty? %> month = "<%= article.month %>", <br>
      <% end %>
      <% if not article.note.empty? %> note = "<%= article.note %>", <br>
      <% end %>
      <% if not article.key.empty? %> key = "<%= article.key %>", <br>
      <% end %>
      }
    </p>
<% end %>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <h3>Required fields: </h3>

    <div class="field">
    <%= f.label :citation_key %><br>
    <%= f.text_field :citation_key %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :journal %><br>
    <%= f.text_field :journal %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>

    <h3>Optional fields: </h3>

    <div class="field">
    <%= f.label :volume %><br>
    <%= f.text_field :volume %>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :pages %><br>
    <%= f.text_field :pages %>
  </div>
  <div class="field">
    <%= f.label :month %><br>
    <%= f.text_field :month %>
  </div>
  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_field :note %>
  </div>
    <div class="field">
      <%= f.label :key %><br>
      <%= f.text_field :key %>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Articles</h1>

<table>
  <thead>
    <tr>
      <th>Citation key</th>
      <th>Author</th>
      <th>Title</th>
      <th>Journal</th>
      <th>Volume</th>
      <th>Year</th>
      <th>Number</th>
      <th>Pages</th>
      <th>Month</th>
      <th>Note</th>
      <th>Key</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.citation_key %></td>
        <td><%= article.author %></td>
        <td><%= article.title %></td>
        <td><%= article.journal %></td>
        <td><%= article.volume %></td>
        <td><%= article.year %></td>
        <td><%= article.number %></td>
        <td><%= article.pages %></td>
        <td><%= article.month %></td>
        <td><%= article.note %></td>
        <td><%= article.key %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Citation key:</strong>
  <%= @article.citation_key %>
</p>

<p>
  <strong>Author:</strong>
  <%= @article.author %>
</p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Journal:</strong>
  <%= @article.journal %>
</p>

<p>
  <strong>Year:</strong>
  <%= @article.year %>
</p>

<% if not @article.volume.empty? %>
    <p>
      <strong>Volume:</strong>
      <%= @article.volume %>
    </p>
<% end %>

<% if not @article.number<0 %>
    <p>
      <strong>Number:</strong>
      <%= @article.number %>
    </p>
<% end %>

<% if not @article.pages.empty? %>
    <p>
      <strong>Pages:</strong>
      <%= @article.pages %>
    </p>
<% end %>

<% if not @article.month.empty? %>
    <p>
      <strong>Month:</strong>
      <%= @article.month %>
    </p>
<% end %>

<% if not @article.note.empty? %>
    <p>
      <strong>Note:</strong>
      <%= @article.note %>
    </p>
<% end %>

<% if not @article.key.empty? %>
    <p>
      <strong>Key:</strong>
      <%= @article.key %>
    </p>
<% end %>

<h3>In BibTeX format:</h3>

<p>@article{<%= @article.citation_key %>,<br>
  author = "<%= @article.author %>", <br>
  title = "<%= @article.title %>",<br>
  booktitle = "<%= @article.journal %>",<br>
  year = <%= @article.year %>, <br>
  <% if not @article.volume.empty? %> volume = "<%= @article.volume %>", <br>
  <% end %>
  <% if not @article.number<0 %> number = "<%= @article.number %>", <br>
  <% end %>
  <% if not @article.pages.empty? %> pages = "<%= @article.pages %>", <br>
  <% end %>
  <% if not @article.month.empty? %> month = "<%= @article.month %>", <br>
  <% end %>
  <% if not @article.note.empty? %> note = "<%= @article.note %>", <br>
  <% end %>
  <% if not @article.key.empty? %> key = "<%= @article.key %>", <br>
  <% end %>
  }
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h3>Required fields: </h3>

  <div class="field">
    <%= f.label :citation_key %><br>
    <%= f.text_field :citation_key %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :publisher %><br>
    <%= f.text_field :publisher %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>

  </div>

  <h3>Optional fields: </h3>

  <div class="field">
    <%= f.label :volume %><br>
    <%= f.text_field :volume %>
  </div>
  <div class="field">
    <%= f.label :series %><br>
    <%= f.text_field :series %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :edition %><br>
    <%= f.text_field :edition %>
  </div>
  <div class="field">
    <%= f.label :month %><br>
    <%= f.text_field :month %>
  </div>
  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_field :note %>
  </div>
  <div class="field">
    <%= f.label :key %><br>
    <%= f.text_field :key %>
  </div>
  <div class="actions">
    <%= f.submit "Luo" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Books</h1>

<table>
  <thead>
    <tr>
      <th>Citation key</th>
      <th>Author</th>
      <th>Title</th>
      <th>Publisher</th>
      <th>Year</th>
      <th>Volume</th>
      <th>Series</th>
      <th>Address</th>
      <th>Edition</th>
      <th>Month</th>
      <th>Note</th>
      <th>Key</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.citation_key %></td>
        <td><%= book.author %></td>
        <td><%= book.title %></td>
        <td><%= book.publisher %></td>
        <td><%= book.year %></td>
        <td><%= book.volume %></td>
        <td><%= book.series %></td>
        <td><%= book.address %></td>
        <td><%= book.edition %></td>
        <td><%= book.month %></td>
        <td><%= book.note %></td>
        <td><%= book.key %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Citation key:</strong>
  <%= @book.citation_key %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Publisher:</strong>
  <%= @book.publisher %>
</p>

<p>
  <strong>Year:</strong>
  <%= @book.year %>
</p>
<% if not @book.volume.empty? %>
  <p>
    <strong>Volume:</strong>
    <%= @book.volume %>
  </p>
<% end %>

<% if not @book.series.empty? %>
  <p>
    <strong>Series:</strong>
    <%= @book.series %>
  </p>
<% end %>

<% if not @book.address.empty? %>
  <p>
    <strong>Address:</strong>
    <%= @book.address %>
  </p>
<% end %>

<% if not @book.edition.empty? %>
  <p>
    <strong>Edition:</strong>
    <%= @book.edition %>
  </p>
<% end %>

<% if not @book.month.empty? %>
  <p>
    <strong>Month:</strong>
    <%= @book.month %>
  </p>
<% end %>

<% if not @book.note.empty? %>
  <p>
    <strong>Note:</strong>
    <%= @book.note %>
  </p>
<% end %>
<% if not @book.key.empty? %>
  <p>
    <strong>Key:</strong>
    <%= @book.key %>
  </p>
<% end %>
<h3>In BibTeX format:</h3>

<p>@Book{<%= @book.citation_key %>,<br>
  author = "<%= @book.author %>", <br>
  title = "<%= @book.title %>",<br>
  publisher = "<%= @book.publisher %>",<br>
  year = <%= @book.year %>, <br>
  <% if not @book.volume.empty? %> volume = "<%= @book.volume %>", <br>  <% end %>
  <% if not @book.series.empty? %> series = "<%= @book.series %>", <br> <% end %>
  <% if not @book.address.empty? %> address = "<%= @book.address %>", <br> <% end %>
  <% if not @book.edition.empty? %> edition = "<%= @book.edition %>", <br> <% end %>
  <% if not @book.month.empty? %> month = "<%= @book.month %>", <br> <% end %>
  <% if not @book.note.empty? %> note = "<%= @book.note %>", <br> <% end %>
  <% if not @book.key.empty? %> key = "<%= @book.key %>", <br> <% end %>
}
</p>
<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/inproceedings/_form.html.erb
<%= form_for(@inproceeding) do |f| %>
  <% if @inproceeding.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inproceeding.errors.count, "error") %> prohibited this inproceeding from being saved:</h2>

      <ul>
      <% @inproceeding.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <h3>Required fields: </h3>

    <div class="field">
    <%= f.label :citation_key %><br>
    <%= f.text_field :citation_key %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :booktitle %><br>
    <%= f.text_field :booktitle %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>

  <h3>Optional fields: </h3>

  <div class="field">
    <%= f.label :editor %><br>
    <%= f.text_field :editor %>
  </div>
  <div class="field">
    <%= f.label :pages %><br>
    <%= f.text_field :pages %>
  </div>
  <div class="field">
    <%= f.label :organization %><br>
    <%= f.text_field :organization %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :month %><br>
    <%= f.text_field :month %>
  </div>
  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_field :note %>
  </div>
  <div class="field">
    <%= f.label :key %><br>
    <%= f.text_field :key %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inproceedings/edit.html.erb
<h1>Editing Inproceeding</h1>

<%= render 'form' %>

<%= link_to 'Show', @inproceeding %> |
<%= link_to 'Back', inproceedings_path %>

app/views/inproceedings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Inproceedings</h1>

<table>
  <thead>
    <tr>
      <th>Citation key</th>
      <th>Author</th>
      <th>Title</th>
      <th>Booktitle</th>
      <th>Year</th>
      <th>Editor</th>
      <th>Pages</th>
      <th>Organization</th>
      <th>Address</th>
      <th>Month</th>
      <th>Note</th>
      <th>Key</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inproceedings.each do |inproceeding| %>
      <tr>
        <td><%= inproceeding.citation_key %></td>
        <td><%= inproceeding.author %></td>
        <td><%= inproceeding.title %></td>
        <td><%= inproceeding.booktitle %></td>
        <td><%= inproceeding.year %></td>
        <td><%= inproceeding.editor %></td>
        <td><%= inproceeding.pages %></td>
        <td><%= inproceeding.organization %></td>
        <td><%= inproceeding.address %></td>
        <td><%= inproceeding.month %></td>
        <td><%= inproceeding.note %></td>
        <td><%= inproceeding.key %></td>
        <td><%= link_to 'Show', inproceeding %></td>
        <td><%= link_to 'Edit', edit_inproceeding_path(inproceeding) %></td>
        <td><%= link_to 'Destroy', inproceeding, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inproceeding', new_inproceeding_path %>

app/views/inproceedings/new.html.erb
<h1>New Inproceeding</h1>

<%= render 'form' %>

<%= link_to 'Back', inproceedings_path %>

app/views/inproceedings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Citation key:</strong>
  <%= @inproceeding.citation_key %>
</p>

<p>
  <strong>Author:</strong>
  <%= @inproceeding.author %>
</p>

<p>
  <strong>Title:</strong>
  <%= @inproceeding.title %>
</p>

<p>
  <strong>Booktitle:</strong>
  <%= @inproceeding.booktitle %>
</p>

<p>
  <strong>Year:</strong>
  <%= @inproceeding.year %>
</p>

<% if not @inproceeding.editor.empty? %>
    <p>
      <strong>Editor:</strong>
      <%= @inproceeding.editor %>
    </p>
<% end %>

<% if not @inproceeding.pages.empty? %>
    <p>
      <strong>Pages:</strong>
      <%= @inproceeding.pages %>
    </p>
<% end %>

<% if not @inproceeding.organization.empty? %>
    <p>
      <strong>Organization:</strong>
      <%= @inproceeding.organization %>
    </p>
<% end %>

<% if not @inproceeding.address.empty? %>
    <p>
      <strong>Address:</strong>
      <%= @inproceeding.address %>
    </p>
<% end %>

<% if not @inproceeding.month.empty? %>
    <p>
      <strong>Month:</strong>
      <%= @inproceeding.month %>
    </p>
<% end %>

<% if not @inproceeding.note.empty? %>
    <p>
      <strong>Note:</strong>
      <%= @inproceeding.note %>
    </p>
<% end %>

<% if not @inproceeding.key.empty? %>
    <p>
      <strong>Key:</strong>
      <%= @inproceeding.key %>
    </p>
<% end %>

<h3>In BibTeX format:</h3>

<p>@inproceedings{<%= @inproceeding.citation_key %>,<br>
  author = "<%= @inproceeding.author %>", <br>
  title = "<%= @inproceeding.title %>",<br>
  booktitle = "<%= @inproceeding.booktitle %>",<br>
  year = <%= @inproceeding.year %>, <br>
  <% if not @inproceeding.editor.empty? %> editor = "<%= @inproceeding.editor %>", <br>  <% end %>
  <% if not @inproceeding.pages.empty? %> pages = "<%= @inproceeding.pages %>", <br> <% end %>
  <% if not @inproceeding.organization.empty? %> organization = "<%= @inproceeding.organization %>", <br> <% end %>
  <% if not @inproceeding.address.empty? %> address = "<%= @inproceeding.address %>", <br> <% end %>
  <% if not @inproceeding.month.empty? %> month = "<%= @inproceeding.month %>", <br> <% end %>
  <% if not @inproceeding.note.empty? %> note = "<%= @inproceeding.note %>", <br> <% end %>
  <% if not @inproceeding.key.empty? %> key = "<%= @inproceeding.key %>", <br> <% end %>
  }
</p>

<%= link_to 'Edit', edit_inproceeding_path(@inproceeding) %> |
<%= link_to 'Back', inproceedings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Referencegenerator</title>
  <%= stylesheet_link_tag    'application', media: 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navibar">
    <%= link_to 'articles', articles_path %>
    <%= link_to 'inproceedings', inproceedings_path%>
    <%= link_to 'books', books_path %>
    <%= link_to 'all', root_path %>

  </div>
  <%= yield %>

</body>
</html>